### ISSUE TITLE
(nickmoen) Needs smooth jazz.

### ISSUE THREAD

**Issue by pompom728** [Mykachow-com/mykachow-com.github.io#3]
No jazz on mykachow.com/nickmoen/

Needs jazz.

**Comment by pompom728** [comment]
Possible Jazz leads. Currently I'm "testing" them to check for ads and what not.

http://cloudrad.io/smoothjazz/player.html
http://www.jazzradio.com/smoothjazz

**Comment by ayancey** [comment]
The 2nd link is what we used before. It definitely won't work.

On Wednesday, February 24, 2016, pompom728 <notifications@github.com> wrote:

> Possible Jazz leads. Currently I'm "testing" them to check for ads and
> what not.
>
> http://cloudrad.io/smoothjazz/player.html
> http://www.jazzradio.com/smoothjazz
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mykachow-com/mykachow-com.github.io/issues/3#issuecomment-188131937>
> .
>


-- 
- Alex Yancey
